/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.VitalInfo;
import Model.VitalInfoHistory;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;



/**
 *
 * @author HP
 */
public class CreateJPanel extends javax.swing.JFrame {

    /**
     * Creates new form CreateJPanel
     * @param History
     */
    VitalInfoHistory History;
    public CreateJPanel(VitalInfoHistory History) {
        initComponents();
        this.History=History;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblModelNum = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblOccupancy = new javax.swing.JLabel();
        lblManCertificate = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtModelNum = new javax.swing.JTextField();
        txtManufacturer = new javax.swing.JTextField();
        txtOccupancy = new javax.swing.JTextField();
        txtManCertificate = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        lblCar_Availability = new javax.swing.JLabel();
        lblBrandName = new javax.swing.JLabel();
        lblManDate = new javax.swing.JLabel();
        ComboBoxCity = new javax.swing.JComboBox<>();
        ComboBoxBrandName = new javax.swing.JComboBox<>();
        DateChooserManDate = new com.toedter.calendar.JDateChooser();
        btnSave = new javax.swing.JButton();
        ComboBoxCar_Availability = new javax.swing.JComboBox<>();
        lblSeat_Capacity = new javax.swing.JLabel();
        ComboBoxSeat_Capacity = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Car Search System");

        lblModelNum.setText("Model Number:");

        lblManufacturer.setText("Manufacturer:");

        lblOccupancy.setText("Occupancy:");

        lblManCertificate.setText("Man. Certificate:");

        lblSerialNumber.setText("Serial Number:");

        lblCity.setText("City:");

        lblCar_Availability.setText("Car_Avaibility:");

        lblBrandName.setText("Brand Name:");

        lblManDate.setText("Manufacturing Year:");

        ComboBoxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "US", "Europe", "Australia" }));

        ComboBoxBrandName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda", "Toyota", "Audi", "BMW" }));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        ComboBoxCar_Availability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        lblSeat_Capacity.setText("Seat_Capacity:");

        ComboBoxSeat_Capacity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSeat_Capacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblManDate, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(lblBrandName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCar_Availability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblModelNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOccupancy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblManCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DateChooserManDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModelNum)
                                    .addComponent(txtManufacturer)
                                    .addComponent(txtOccupancy)
                                    .addComponent(txtManCertificate)
                                    .addComponent(txtSerialNumber)
                                    .addComponent(ComboBoxCity, 0, 80, Short.MAX_VALUE)
                                    .addComponent(ComboBoxBrandName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ComboBoxCar_Availability, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBoxSeat_Capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(227, 227, 227)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTitle)
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblModelNum)
                                            .addComponent(txtModelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblManufacturer)
                                            .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblOccupancy))
                                    .addComponent(txtOccupancy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblManCertificate))
                            .addComponent(txtManCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSerialNumber))
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCar_Availability)
                        .addGap(18, 18, 18)
                        .addComponent(lblBrandName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBoxCar_Availability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManDate)
                    .addComponent(DateChooserManDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(lblSeat_Capacity)
                    .addComponent(ComboBoxSeat_Capacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        DateFormat dateFormat =new SimpleDateFormat("YYYY");
        
        
        
        
        
        int model_num=Integer.parseInt(txtModelNum.getText());
        String manufacturer = txtManufacturer.getText();
        int Occupancy= Integer.parseInt(txtOccupancy.getText());
        String manu_Certi= txtManCertificate.getText();
        int serial_num= Integer.parseInt(txtSerialNumber.getText());
        String city= ComboBoxCity.getSelectedItem().toString();
        boolean Car_Availability= Boolean.parseBoolean(ComboBoxCar_Availability.getActionCommand());
        String Brand_Name= ComboBoxBrandName.getSelectedItem().toString();
        String Man_Date= dateFormat.format(DateChooserManDate.getDate());
        String Seat_Capacity= ComboBoxSeat_Capacity.getSelectedItem().toString();
        
        
        VitalInfo vih = History.addNewVitals();
        
        vih.setModel_num(model_num);
        vih.setManufacturer(manufacturer);
        vih.setOccupancy(Occupancy);
        vih.setMan_Certi(manu_Certi);
        vih.setSerial_num(serial_num);
        vih.setCity(city);
        vih.setCar_Availability(Car_Availability);
        vih.setBrand_Name(Brand_Name);
        vih.setMan_Date(Man_Date);                                        
        vih.setSeat_Capacity(Seat_Capacity);     
        
        JOptionPane.showMessageDialog(this, "New Vital Info added.");
        
        txtModelNum.setText("");
        txtManufacturer.setText("");
        txtOccupancy.setText("");
        txtManCertificate.setText("");
        txtSerialNumber.setText("");
        ComboBoxCity.setSelectedItem("");
        ComboBoxCar_Availability.setActionCommand("");
        ComboBoxBrandName.setSelectedItem("");
        DateChooserManDate.setDateFormatString("");
        ComboBoxSeat_Capacity.setSelectedItem("");
        
        
        
        
        
      
      
        
      
        
      
      
      
    }//GEN-LAST:event_btnSaveActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxBrandName;
    private javax.swing.JComboBox<String> ComboBoxCar_Availability;
    private javax.swing.JComboBox<String> ComboBoxCity;
    private javax.swing.JComboBox<String> ComboBoxSeat_Capacity;
    private com.toedter.calendar.JDateChooser DateChooserManDate;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblBrandName;
    private javax.swing.JLabel lblCar_Availability;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblManCertificate;
    private javax.swing.JLabel lblManDate;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblModelNum;
    private javax.swing.JLabel lblOccupancy;
    private javax.swing.JLabel lblSeat_Capacity;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtManCertificate;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtModelNum;
    private javax.swing.JTextField txtOccupancy;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
